INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(1, 'example1', 1, 2003, 1, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(2, 'example2', 1, 2050, 5350, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(3, 'example3', 1, 2050, 5351, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(4, 'example4', 1, 2050, 5352, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(5, 'example5', 1, 2050, 5353, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(6, 'example6', 1, 2050, 5354, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(7, 'example7', 1, 2050, 5355, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(8, 'example8', 1, 2050, 5356, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(9, 'example9', 1, 2050, 5357, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(10, 'example10', 1, 2050, 5358, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(11, 'example11', 1, 2050, 5359, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(12, 'example12', 1, 2100, 5360, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(13, 'example13', 1, 2100, 5361, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(14, 'example14', 1, 2100, 5362, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(15, 'example15', 1, 2100, 5363, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(16, 'example16', 1, 2100, 5400, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(17, 'example17', 1, 2100, 5401, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(18, 'example18', 1, 2100, 5402, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(19, 'example19', 1, 2100, 5450, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(20, 'example20', 1, 2100, 5451, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(21, 'example21', 1, 2100, 5452, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(22, 'example22', 1, 2100, 5453, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(23, 'example23', 1, 2100, 5454, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(24, 'example24', 1, 2100, 5455, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(25, 'example25', 1, 2150, 5456, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(26, 'example26', 1, 2150, 5457, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(27, 'example27', 1, 2150, 5458, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(28, 'example28', 1, 2150, 5459, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(29, 'example29', 1, 2150, 5460, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(30, 'example30', 1, 2150, 5461, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(31, 'example31', 1, 2150, 5462, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(32, 'example32', 1, 2150, 5463, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(33, 'example33', 1, 2150, 5464, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(34, 'example34', 1, 2150, 5465, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(35, 'example35', 1, 2150, 5466, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(36, 'example36', 1, 2150, 5467, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(37, 'example37', 1, 2150, 5468, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(38, 'example38', 1, 2150, 5469, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(39, 'example39', 1, 2150, 5470, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(40, 'example40', 1, 2150, 5471, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(41, 'example41', 1, 2150, 5472, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(42, 'example42', 1, 2150, 5473, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(43, 'example43', 1, 3000, 5474, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(44, 'example44', 1, 3000, 5475, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(45, 'example45', 1, 2, 5477, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(46, 'example46', 1, 2, 5478, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(47, 'example47', 1, 2, 5479, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(48, 'example48', 1, 3002, 5480, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(49, 'example49', 1, 3002, 5481, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(50, 'example50', 1, 3003, 5482, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(51, 'example51', 1, 3003, 5483, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(52, 'example52', 1, 3004, 5484, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(53, 'example53', 1, 3004, 5485, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(54, 'example54', 1, 3005, 5486, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(55, 'example55', 1, 3005, 5487, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(56, 'example56', 1, 3006, 5488, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(57, 'example57', 1, 3006, 5489, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(58, 'example58', 1, 3003, 5490, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(59, 'example59', 1, 2150, 5500, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(60, 'example60', 1, 2150, 5501, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(61, 'example61', 1, 2150, 5502, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(62, 'example62', 1, 2200, 5503, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(63, 'example63', 1, 2200, 5504, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(64, 'example64', 1, 2200, 5505, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(65, 'example65', 1, 2200, 5506, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(66, 'example66', 1, 2200, 5507, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(67, 'example67', 1, 2200, 5508, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(68, 'example68', 1, 2200, 5509, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(69, 'example69', 1, 2200, 5510, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(70, 'example70', 1, 2200, 5511, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(71, 'example71', 1, 2200, 5512, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(72, 'example72', 1, 2200, 5513, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(73, 'example73', 1, 2200, 5514, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(74, 'example74', 1, 2200, 5515, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(75, 'example75', 1, 2200, 5516, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(76, 'example76', 1, 2200, 5517, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(77, 'example77', 1, 2200, 5518, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(78, 'example78', 1, 2200, 5519, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(79, 'example79', 1, 1, 5520, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(80, 'example80', 1, 1, 5521, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(81, 'example81', 1, 1, 5522, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(82, 'example82', 1, 1, 5523, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(83, 'example83', 1, 1, 5524, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(84, 'example84', 1, 1, 5525, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(85, 'example85', 1, 1, 5526, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(86, 'example86', 1, 1, 5527, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(87, 'example87', 1, 1, 5528, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(88, 'example88', 1, 1, 5529, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(89, 'example89', 1, 1, 5530, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(90, 'example90', 1, 1, 5531, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(91, 'example91', 1, 1, 5532, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(92, 'example92', 1, 1, 5533, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(93, 'example93', 1, 1, 5534, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(94, 'example94', 1, 1, 5535, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(95, 'example95', 1, 1, 5536, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(96, 'example96', 1, 1, 5537, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(97, 'example97', 1, 1, 5538, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(98, 'example98', 1, 1, 5539, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(99, 'example99', 1, 2150, 5540, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(100, 'example100', 1, 3, 6000, 'QC_TRAINEE','Undefined', systimestamp, 0);


INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(101, 'batchNote101', 1, 1, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(102, 'batchNote102', 1, 2, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(103, 'batchNote103', 1, 3, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(104, 'batchNote104', 1, 2003, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(105, 'batchNote105', 1, 2050, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(106, 'batchNote106', 1, 2100, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(107, 'batchNote107', 1, 2150, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(108, 'batchNote108', 1, 2200, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(109, 'batchNote109', 1, 3000, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(110, 'batchNote110', 1, 3002, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(111, 'batchNote111', 1, 3003, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(112, 'batchNote112', 1, 3004, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(113, 'batchNote113', 1, 3005, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(114, 'batchNote114', 1, 3006, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(115, 'example115', 2, 2003, 1, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(116, 'example116', 2, 2050, 5350, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(117, 'example117', 2, 2050, 5351, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(118, 'example118', 2, 2050, 5352, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(119, 'example119', 2, 2050, 5353, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(120, 'example120', 2, 2050, 5354, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(121, 'example121', 2, 2050, 5355, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(122, 'example122', 2, 2050, 5356, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(123, 'example123', 2, 2050, 5357, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(124, 'example124', 2, 2050, 5358, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(125, 'example125', 2, 2050, 5359, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(126, 'example126', 2, 2100, 5360, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(127, 'example127', 2, 2100, 5361, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(128, 'example128', 2, 2100, 5362, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(129, 'example129', 2, 2100, 5363, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(130, 'example130', 2, 2100, 5400, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(131, 'example131', 2, 2100, 5401, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(132, 'example132', 2, 2100, 5402, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(133, 'example133', 2, 2100, 5450, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(134, 'example134', 2, 2100, 5451, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(135, 'example135', 2, 2100, 5452, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(136, 'example136', 2, 2100, 5453, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(137, 'example137', 2, 2100, 5454, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(138, 'example138', 2, 2100, 5455, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(139, 'example139', 2, 2150, 5456, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(140, 'example140', 2, 2150, 5457, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(141, 'example141', 2, 2150, 5458, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(142, 'example142', 2, 2150, 5459, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(143, 'example143', 2, 2150, 5460, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(144, 'example144', 2, 2150, 5461, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(145, 'example145', 2, 2150, 5462, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(146, 'example146', 2, 2150, 5463, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(147, 'example147', 2, 2150, 5464, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(148, 'example148', 2, 2150, 5465, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(149, 'example149', 2, 2150, 5466, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(150, 'example150', 2, 2150, 5467, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(151, 'example151', 2, 2150, 5468, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(152, 'example152', 2, 2150, 5469, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(153, 'example153', 2, 2150, 5470, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(154, 'example154', 2, 2150, 5471, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(155, 'example155', 2, 2150, 5472, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(156, 'example156', 2, 2150, 5473, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(157, 'example157', 2, 3000, 5474, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(158, 'example158', 2, 3000, 5475, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(159, 'example159', 2, 2, 5477, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(160, 'example160', 2, 2, 5478, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(161, 'example161', 2, 2, 5479, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(162, 'example162', 2, 3002, 5480, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(163, 'example163', 2, 3002, 5481, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(164, 'example164', 2, 3003, 5482, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(165, 'example165', 2, 3003, 5483, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(166, 'example166', 2, 3004, 5484, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(167, 'example167', 2, 3004, 5485, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(168, 'example168', 2, 3005, 5486, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(169, 'example169', 2, 3005, 5487, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(170, 'example170', 2, 3006, 5488, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(171, 'example171', 2, 3006, 5489, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(172, 'example172', 2, 3003, 5490, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(173, 'example173', 2, 2150, 5500, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(174, 'example174', 2, 2150, 5501, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(175, 'example175', 2, 2150, 5502, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(176, 'example176', 2, 2200, 5503, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(177, 'example177', 2, 2200, 5504, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(178, 'example178', 2, 2200, 5505, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(179, 'example179', 2, 2200, 5506, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(180, 'example180', 2, 2200, 5507, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(181, 'example181', 2, 2200, 5508, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(182, 'example182', 2, 2200, 5509, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(183, 'example183', 2, 2200, 5510, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(184, 'example184', 2, 2200, 5511, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(185, 'example185', 2, 2200, 5512, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(186, 'example186', 2, 2200, 5513, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(187, 'example187', 2, 2200, 5514, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(188, 'example188', 2, 2200, 5515, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(189, 'example189', 2, 2200, 5516, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(190, 'example190', 2, 2200, 5517, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(191, 'example191', 2, 2200, 5518, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(192, 'example192', 2, 2200, 5519, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(193, 'example193', 2, 1, 5520, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(194, 'example194', 2, 1, 5521, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(195, 'example195', 2, 1, 5522, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(196, 'example196', 2, 1, 5523, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(197, 'example197', 2, 1, 5524, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(198, 'example198', 2, 1, 5525, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(199, 'example199', 2, 1, 5526, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(200, 'example200', 2, 1, 5527, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(201, 'example201', 2, 1, 5528, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(202, 'example202', 2, 1, 5529, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(203, 'example203', 2, 1, 5530, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(204, 'example204', 2, 1, 5531, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(205, 'example205', 2, 1, 5532, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(206, 'example206', 2, 1, 5533, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(207, 'example207', 2, 1, 5534, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(208, 'example208', 2, 1, 5535, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(209, 'example209', 2, 1, 5536, 'QC_TRAINEE','Superstar', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(210, 'example210', 2, 1, 5537, 'QC_TRAINEE','Average', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(211, 'example211', 2, 1, 5538, 'QC_TRAINEE','Poor', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(212, 'example212', 2, 1, 5539, 'QC_TRAINEE','Good', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(213, 'example213', 2, 2150, 5540, 'QC_TRAINEE','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(214, 'example214', 2, 3, 6000, 'QC_TRAINEE','Poor', systimestamp, 0);


INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(215, 'batchNote215', 2, 1, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(216, 'batchNote216', 2, 2, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(217, 'batchNote217', 2, 3, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(218, 'batchNote218', 2, 2003, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(219, 'batchNote219', 2, 2050, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(220, 'batchNote220', 2, 2100, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(221, 'batchNote221', 2, 2150, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(222, 'batchNote222', 2, 2200, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(223, 'batchNote223', 2, 3000, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(224, 'batchNote224', 2, 3002, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(225, 'batchNote225', 2, 3003, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(226, 'batchNote226', 2, 3004, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(227, 'batchNote227', 2, 3005, 0, 'QC_BATCH','Undefined', systimestamp, 0);
INSERT INTO CALIBER_NOTE (NOTE_ID, NOTE_CONTENT, WEEK_NUMBER, BATCH_ID, TRAINEE_ID, NOTE_TYPE, QC_STATUS, UPDATE_TIME, LAST_SAVED_BY)
VALUES(228, 'batchNote228', 2, 3006, 0, 'QC_BATCH','Undefined', systimestamp, 0);
COMMIT;